### ISSUE TITLE
Design System - Block Buttons - Update Width and Height

### ISSUE THREAD

**Issue by jdrf-digitaldesigner** [JDRF/design-system#115]
The block buttons' width should be a multiple of 4, and height should be 40px. 

Thx,

Ismael

**Comment by RachelRVasquez** [comment]
@fuhton 
This bug was submitted for PR on issue #109.

Looks like we had the markup using the "large" version of the block buttons however. Submitted another PR to reflect the normal sized block buttons which will be 40px height with the above issue closed out.

https://github.com/JDRF/design-system/pull/125

**Comment by fuhton** [comment]
Merged

**Comment by fuhton** [comment]
@jdrf-digitaldesigner Can you review and confirm?

**Comment by jdrf-digitaldesigner** [comment]
Confirmed. Thx!
