### ISSUE TITLE
Design System - Button Toolbar - Toggle Not Functioning Properly

### ISSUE THREAD

**Issue by jdrf-digitaldesigner** [JDRF/design-system#117]
The Button Toolbar (Toggle Bar) should display one selected element at a time (toggle).

**Comment by RachelRVasquez** [comment]
@jdrf-digitaldesigner @pmmck 

There are two different components in Bootstrap. One is the toggle states applied only to a single button or a button group of checkboxes/radio buttons:

http://v4-alpha.getbootstrap.com/components/buttons/#toggle-states

The second component is a button group set as a button toolbar that does not have toggle states:

http://v4-alpha.getbootstrap.com/components/button-group/#button-toolbar

I just want to confirm which of the two components we're applying to this as we may have tried to combine components when Bootstrap isn't set up to work that way.

**Comment by jdrf-digitaldesigner** [comment]
It should function like the Button-toolbar example: http://v4-alpha.getbootstrap.com/components/button-group/#button-toolbar

Thx

**Comment by RachelRVasquez** [comment]
@pmmck @jdrf-digitaldesigner 

I'm currently working on this ticket and noticed the height of 40px we placed on the buttons isn't giving the icon the correct room to be vertically centered. With the correct icon font size and line height (20px) as well as the top/bottom padding (10px), the natural height of this button would be 44px instead of 40px. Should we let these buttons remain their natural height to keep the correct measurements and allow these icons to vertically align rather than enforce a 40px height?

cc: @fuhton

**Comment by RachelRVasquez** [comment]
Disregard deleted comment about vertical alignment - it appears there was a 2px interfering.

**Comment by RachelRVasquez** [comment]
@fuhton 

Submitted 2 PRs:

https://github.com/JDRF/design-system/pull/156

https://github.com/JDRF/design-system/pull/157

**Comment by fuhton** [comment]
Merged. @pmmck @jdrf-digitaldesigner Please confirm.

**Comment by jdrf-digitaldesigner** [comment]
Confirmed. Thx!
