### ISSUE TITLE
Icon Button Size

### ISSUE THREAD

**Issue by jdrf-digitaldesigner** [JDRF/design-system#119]
The Icon Left and Icon Right buttons are not currently listed in the design system. 

Thx,

Ismael

**Comment by RachelRVasquez** [comment]
@jdrf-digitaldesigner 

These are currently displayed in the icons section:

http://jdrf.github.io/design-system/dist/content.html#icons

**Comment by pmmck** [comment]
@RachelRVasquez can we move them into the buttons section?

cc @jdrf-digitaldesigner

**Comment by fuhton** [comment]
@pmmck @jdrf-digitaldesigner Should we move "Icon Only Buttons" to the Buttons section as well?

**Comment by jdrf-digitaldesigner** [comment]
Yes, please move "Icon-only Buttons" to the Buttons section as well. Thx

**Comment by RachelRVasquez** [comment]
@fuhton Submitted two PRs:

https://github.com/JDRF/design-system/pull/159

https://github.com/JDRF/design-system/pull/160

**Comment by fuhton** [comment]
Merged.

**Comment by fuhton** [comment]
@jdrf-digitaldesigner This is ready for you to review and close.

**Comment by jdrf-digitaldesigner** [comment]
Can you please update the button sizes to: 48px, 40px, and 32px (height)? Thx

**Comment by briansaycocie** [comment]
@jdrf-digitaldesigner I've adjusted the icon sizes in each button so it matches the Zeplin specs (24px, 20px, 16px), however adding the icon inside the button increases the height of the button just slightly that it's no longer 48px, 40px, 32px but instead 60px, 48px, 36px. We can reduce the size of the icons so it's more inline with 48px, 40px, 32px but I wanted to get your thoughts before I proceed.

**Comment by pmmck** [comment]
@briansaycocie how about a `.has-icon` class that when applied to a button reduces the vertical padding?  That way we can keep the buttons sizes consistent and use bigger icons that are easier to read.  Thoughts?

cc @RachelRVasquez @jdrf-digitaldesigner

**Comment by fuhton** [comment]
Seems like too many classes to be added.

**Comment by pmmck** [comment]
Adding 3 new button heights is not an option because they will change the balance of the layout.  And decreasing the icon size is not an option because of minimum legibility sizes — and they just look better.

The two solutions I can think of are:

1. Adding a modifier like `.has-icon` to existing buttons.
2. Creating new buttons.

The downside of the modifier approach is that you have to add an additional class to the HTML.  

The downside of the new button approach is that we would double the amount of button css we need to maintain.  If we changed the the core button style we would need to also make that update in the icon button variation.

Seems to me like option 1 is the way to go.

Is there a third option I'm not thinking of?

@fuhton @RachelRVasquez @briansaycocie @jdrf-digitaldesigner

**Comment by RachelRVasquez** [comment]
@pmmck I originally removed any height restrictions on the icon buttons so we can let the icons determine the height. Forcing a height on the left/right icon buttons as well as the icon button toolbar won't guarantee vertical alignment due to the unknown icons that will be swapped out. Since we can't predict what icons will be used, it makes sense to keep them as maintainable as possible by letting the padding decide the buttons height - only for buttons with icons. This can be adjusted on a per project basis with overwrites in that project.

I agree with Nick on avoiding the addition of more classes than necessary. Changing the icons size as Patrick mentioned, can interfere with legibility - not to mention one icon may work well at one size whereas another won't. Take the facebook/twitter icons for example - due to the FB logo being so thin, it's usually enlarged a bit compared to the wider, more legible twitter icon. I know FB/Twitter aren't part of the material design icons, but wanted to reference them for an example of the dilemma we're facing in this ticket.

For maintainability in DS, less classes and less css, we can keep the buttons as is with the icons determining the height. Thoughts?

cc: @briansaycocie @fuhton @jdrf-digitaldesigner

**Comment by pmmck** [comment]
@RachelRVasquez I have to put my foot down here.  We cannot have variations on our button heights.

cc @briansaycocie @fuhton @jdrf-digitaldesigner

**Comment by fuhton** [comment]
@RachelRVasquez 

Material icons are a set size. Let's add another class for icons called `.ds-btn-has-icon` that sets a static height (or reduced padding).

Let's update the docs in the buttons section and the icon section.

**Comment by RachelRVasquez** [comment]
@fuhton I changed the name of the modifier classes so it wouldn't look too similar tp `.ds-btn-icon`. PRs submitted:

https://github.com/JDRF/design-system/pull/242

https://github.com/JDRF/design-system/pull/243

**Comment by fuhton** [comment]
@pmmck Merged. Please confirm.

**Comment by pmmck** [comment]
`.ds-btn-icon` seems to describe the icon.   Isn't the point of this class to describe a situation happening with the button?  

```
$btn-icon-height: 40px;
```

That to me reads as "The icon inside of a button is 40px".  

Whereas `.has-*` is a reusable pattern.   `.nav-has-search`, `.btn-has-icon`, etc.

**Comment by fuhton** [comment]
@pmmck Good point. Sorry I missed this convention.

**Comment by RachelRVasquez** [comment]
@fuhton PRs:

https://github.com/JDRF/design-system/pull/248

https://github.com/JDRF/design-system/pull/249

**Comment by fuhton** [comment]
Merged. @pmmck Please confirm.

**Comment by pmmck** [comment]
LGTM thanks!

**Comment by pmmck** [comment]
@fuhton I realize now that I was only reviewing the code but the buttons are not the correct height in the docs.  Re-opening this issue.

**Comment by fuhton** [comment]
@pmmck I'll need more context regarding this issue?

**Comment by pmmck** [comment]
@fuhton The large button with icon is 58px - it should be 48px.  The primary button is 50px - it should be 40px.  The small button is 42px - it should be 32px.

I'm not sure the current implementation is the best approach.

```
ds-btn ds-btn-primary ds-btn-lg ds-btn-icon ds-btn-has-icon-lg

```

Do we really need both the `.btn-icon` applied to the button?  And then also the `.btn-has-icon-[size]`?

Also, it seems that in the button scss file there is both heights using padding and heights set in pixels.  Do we need to set the heights in pixels if the padding is correct?

**Comment by fuhton** [comment]
@pmmck If you re-review this ticket, the set heights and additional class(es) are something we agreed upon and decided was the best way forward. 

I'll re-review but I believe we can remove the `.btn-has-icon-[size]` class.

**Comment by pmmck** [comment]
@fuhton having set heights as the outcome is absolutely something we want.  There should only be 3 heights for buttons: 32, 40, 48.  

I was talking about what seems to be a mixed approach of declaring a pixel height and using padding.  I would prefer if the padding + line-height + etc = 32, 40, 48.   But perhaps that's just my own personal preference and if it's not the best approach here, I defer to 10up.

**Comment by RachelRVasquez** [comment]
@pmmck @jdrf-digitaldesigner 

To confirm what Patrick's saying, ideally you don't want to declare a fixed height on buttons as in `height: 40px` but to change the padding/line-height so that buttons are those heights naturally? And if so, if it means going against the Zeplin design specs for padding/line-height to get the desired heights - is that ok?

Just want to clarify the task again before jumping back in. Thanks!

cc: @fuhton

**Comment by pmmck** [comment]
@RachelRVasquez 

Where do you see a discrepancy in Zeplin?  This is an example of what I'm seeing where the total heights are equal to 32, 40, 48.

![screen shot 2016-06-23 at 4 22 43 pm](https://cloud.githubusercontent.com/assets/385391/16318852/d3233bb2-395e-11e6-9a63-6436ec7817b4.png)

cc @fuhton @jdrf-digitaldesigner

**Comment by RachelRVasquez** [comment]
@pmmck Right now the buttons do match the Zeplin specs without the `.btn-has-icon-size` class, but we had to go against them due to heights. For the large button for example we have:

- 14px/14px for the font in Gotham Medium
- Padding in the button is 16px Top/Bottom and 24px Left/Right.

![screen shot 2016-06-23 at 4 57 27 pm](https://cloud.githubusercontent.com/assets/10246844/16320421/9217f9a8-3965-11e6-9d8e-5b61c6842cc3.png)


And with the `height: auto` - the natural height that the browser interprets is larger than 48 by 10px. 

![screen shot 2016-06-23 at 5 04 26 pm](https://cloud.githubusercontent.com/assets/10246844/16320430/a368e690-3965-11e6-867d-62365b2b1935.png)


Forcing the 48px height pictured below, cuts off the button. 

![screen shot 2016-06-23 at 5 04 46 pm](https://cloud.githubusercontent.com/assets/10246844/16320435/aceb988e-3965-11e6-96f3-4ec6d1e5292a.png)


So we [had to change](https://github.com/JDRF/design-system/pull/248/files) the padding using the `.btn-has-icon-size` classes if we wanted the browser to reduce the padding and naturally stick to those heights without cutting the button off unevenly. So although Zeplin has those specs for the font size and padding, the height Zeplin has versus what the browser makes it don't match up, so we had to make adjustments to imitate it.

cc: @jdrf-digitaldesigner @fuhton

**Comment by pmmck** [comment]
@RachelRVasquez 

Thanks, that makes sense.   Please ignore the padding in Zeplin and adjust accordingly so that the total heights equal 32, 40, 48px.  Many thanks!

@fuhton @jdrf-digitaldesigner

**Comment by RachelRVasquez** [comment]
@fuhton PRs submitted with updates. Removed the `.btn-has-icon-size` classes/variables/styles and adjusted padding for buttons with icons/text to naturally be these heights.

https://github.com/JDRF/design-system/pull/263

https://github.com/JDRF/design-system/pull/264

**Comment by fuhton** [comment]
@pmmck @jdrf-digitaldesigner This is ready for your review.
