### ISSUE TITLE
Design System - Cards - Size

### ISSUE THREAD

**Issue by jdrf-digitaldesigner** [JDRF/design-system#122]
Cards' width and height should be a multiple of 4px.

Thx,

Ismael

**Comment by RachelRVasquez** [comment]
@jdrf-digitaldesigner 

To keep cards dynamic/responsive, we should avoid restricting the width/heights of them. The Bootstrap grid can help determine widths and on a per project basis where DS is being used, the widths can be overwritten. We want to ensure content will never break out of the cards due to size restrictions.

**Comment by pmmck** [comment]
@RachelRVasquez a good check to see if the line-heights, padding, margins are set correctly is if the total height of a component is a multiple of 4.   Type and icons align to a 4px grid; components align to an 8px grid.

cc @jdrf-digitaldesigner

**Comment by briansaycocie** [comment]
@jdrf-digitaldesigner @pmmck I double checked the values of the line-heights, padding, and margins. This all looks good. Can you please confirm?

**Comment by jdrf-digitaldesigner** [comment]
Confirmed. Thx!
