### ISSUE TITLE
All browsers:  Buttons / Toggle Segments interaction improvements

### ISSUE THREAD

**Issue by McCallumDillon** [JDRF/design-system#49]
![rec2](https://cloud.githubusercontent.com/assets/5239235/15758917/877b6b88-28c1-11e6-889e-f1a78d49dd63.gif)

If these are to act almost like "tabs" then the current interaction of the "Toggle Segment" is strange.

- Would there be an instance of needing to toggle more than one?  If not then, toggling between left/center/right, only 1 should be "active" at a time.

- Would there be an instance where the user could deselect ALL? Currently you can select left/center/right and make all active? If it is a matter of choosing 1 element (like a tab would) as active at a time then we need to adjust how it is currently.

- Currently you can 'deselect' all 3 states by clicking the 'active' state off. Is this intended? IF so, then the strange interaction is that you click it (to deselect) and then it wont actually revert to the default state until you click off the button on the background of the page. IF NOT, and there is 'always' one active element, then we need to make it so you there is at least one active at all times and you can't 'turn them all off'.

**Comment by fuhton** [comment]
1. Referencing the "Radio Buttons" section
2. Feels the same as #1 
3. This is part of bootstrap and the focus class.

I think we should break 3. into it's own ticket.

@McCallumDillon Thoughts?

**Comment by McCallumDillon** [comment]
Yeah. My thought is that the radio buttons differ from checkboxes in that the user can only select one at a time. VS the checkboxes where the user may want to toggle a few items.

**Comment by RachelRVasquez** [comment]
@McCallumDillon @fuhton I think we need to clarify what these buttons are intended to be used for. The Zeplin design has titled them as toggable areas:

http://v4-alpha.getbootstrap.com/components/buttons/#toggle-states

Bootstrap's reference only shows one button to demonstrate the toggle state. For the design, we used button groups shown here on Bootstrap's docs:

http://v4-alpha.getbootstrap.com/components/button-group/#basic-example

So it's as if the two components are being combined into a custom component for DS. Do we have any documentation on how these sections are going to be used? I feel like we can predict what behavior they should have if we get that answer, since we don't exactly have an exact reference from Bootstrap's docs.

**Comment by fuhton** [comment]
I think it's a confusion of terms. All necessary functionality is included already with the Single Toggle ( radio button buttons ) and Multi Toggle ( checkbox buttons ).
