### ISSUE TITLE
IE9/10/11, Windows 7 (desktop) : Button Loading animation not showing

### ISSUE THREAD

**Issue by McCallumDillon** [JDRF/design-system#55]
![screen shot 2016-06-02 at 2 02 21 pm](https://cloud.githubusercontent.com/assets/5239235/15760980/a9ddb984-28ca-11e6-9159-ce5fd7e669f7.jpg)

Where the loading animated circle should be it is blank and just shows a solid green button.

**Comment by briansaycocie** [comment]
I'm also seeing this in IE11, Windows 10.

**Comment by fuhton** [comment]
I'm not seeing the loading animation on any IE browser.

**Comment by RachelRVasquez** [comment]
@fuhton 
Just wanted to provide a status here - after some investigation, part of the issue was the value for `stroke-dasharray` was too high. Adjusting this number and adding a `stroke="#ffffff" to the circle graphic assisted in getting the animation to show in IE11/10. However in IE9, the `animation` syntax is not supported. 

http://caniuse.com/#search=css%20animation

I've added in the auto prefixer on DS so transitions/transforms aren't an issue however there aren't any existing polyfills to support CSS3 animations that I can find. The loading animation we currently have is too complex to re-create with JS although I'd like to confirm other possibilities tomorrow when it isn't EOD.

**Comment by pmmck** [comment]
What do you think about starting with the text "Loading..." and then enhancing with the animated spinner if the browser supports it?  

![loading text](https://cloud.githubusercontent.com/assets/385391/15877424/aba18730-2ce1-11e6-9707-c19cad02ca13.png)

@RachelRVasquez @briansaycocie @fuhton

**Comment by fuhton** [comment]
@RachelRVasquez Let's move forward with the above suggestion after we've completed #66 and #67

**Comment by RachelRVasquez** [comment]
@fuhton 

Submitted a PR for the code changes:

https://github.com/JDRF/design-system/pull/74

And another for documentation:

https://github.com/JDRF/design-system/pull/73

**Comment by RachelRVasquez** [comment]
@fuhton 

Spacing adjusted in PR #74.

**Comment by fuhton** [comment]
Merged and complete
