### ISSUE TITLE
IE9, Windows 7: Color palettes are vertically stacked instead of horizontal

### ISSUE THREAD

**Issue by briansaycocie** [JDRF/design-system#58]
In IE9, the color palettes are vertically stacked instead of being in a horizontal row. The expected behavior is to display as a horizontal row.

Current:
![screenshot 2016-06-02 17 47 16](https://cloud.githubusercontent.com/assets/1328262/15763503/1279c752-28ea-11e6-8969-7340fe48612c.png)

Expected:
![screenshot 2016-06-02 17 46 37](https://cloud.githubusercontent.com/assets/1328262/15763510/190dd0c2-28ea-11e6-912e-7dd4bb3512b4.png)

**Comment by fuhton** [comment]
This is because Flexbox isn't supported in IE9. This is also seen in the browser support for Bootstrap v4 -http://v4-alpha.getbootstrap.com/getting-started/browsers-devices/#internet-explorer-9

**Comment by fuhton** [comment]
@RachelRVasquez It'd be great to add in a polyfill to make this work on Github

**Comment by RachelRVasquez** [comment]
@fuhton I've added 10up's flexibility polyfill successfully. However it seems due to lint errors, it's not applying correctly for IE9 and the colors are displaying as dark grey while still not stacking.

Added the file to the linter when I realized it's been set up like this:
https://github.com/10up/flexibility/blob/master/dist/flexibility.js

The entire file is a single line. Can we exclude or somehow keep this file from breaking everything else due to the linter? Even if it's not added to the scripts-lint.js task, it won't work properly. Thoughts?

**Comment by fuhton** [comment]
We should be requiring this like we've done prismjs.

**Comment by RachelRVasquez** [comment]
This has been required like prismjs from the node modules. There is a console error that is likely the culprit however it is saying that `requestAnimationFrame` is undefined. Doing a search through all files, the only instances of this being used is in node_modules for babel-core and caniuse-db. Thoughts @fuhton?

**Comment by fuhton** [comment]
Let's try a different jQuery version ( prefer jQuery 1.X.X ) to confirm it's not an issue with jQuery

**Comment by RachelRVasquez** [comment]
Tried downgrading to 1.12.4 and it's still giving that error in IE9.

**Comment by fuhton** [comment]
I'll do some digging into this issue.

**Comment by fuhton** [comment]
While this is a "Nice to have", I don't think this ruins the ultimate experience in IE9.
