### ISSUE TITLE
Remove (presumably) unused bootstrap classes

### ISSUE THREAD

**Issue by magnificode** [JDRF/design-system#6]
In the compiled css, there are about 1600 references to .mi- prefixed classes. This class doesn't seem to appear anywhere in the source other than the compiled CSS.

Any chance we could track this down and prevent it from being compiled into the stylesheet?

Start: https://github.com/JDRF/design-system/blob/master/dist/css/design-system.css#L1
End: https://github.com/JDRF/design-system/blob/master/dist/css/design-system.css#L2426

**Comment by magnificode** [comment]
This extends to the `.col` classes as well:

Start: https://github.com/JDRF/design-system/blob/master/dist/css/design-system.css#L3145
End: https://github.com/JDRF/design-system/blob/master/dist/css/design-system.css#L3728

**Comment by RachelRVasquez** [comment]
The `.mi-` classes are from the material icons styles. We're not using all of the icons on the DS itself although for a JDRF site, they may be using them. Since the DS is meant as a visual guide, I agree it'd make sense to remove what we don't need. May need to brainstorm a bit with @fuhton though about approaching it since we're currently copying over the material icons from node_modules and then merging that into the final file. Unless you have some suggestions @magnificode?

Here's the gulp task where the material icons and Bootstrap overwrites are being merged: https://github.com/JDRF/design-system/blob/master/tasks/styles.js

**Comment by RachelRVasquez** [comment]
The `col` classes are being pulled from Bootstrap. We are making use of the grid but only in the examples on the gh-pages branch.

**Comment by magnificode** [comment]
Ah, I see now, it's Monday, and when I view-source'd the site I looked for .col :facepalm:

As far as the `.mi` bit, this may be a bit heavy handed but I know there are some node modules that can run through your compiled CSS and remove unused classes (https://github.com/ben-eb/gulp-uncss)

Perhaps this issue will be solved inherently if we implement a fix for #2. Utilizing SVG instead of the icon-font itself will grant us the ability to not have to import the stylesheet at all.

**Comment by RachelRVasquez** [comment]
After discussing further with @fuhton, we decided that we'd need the entire grid as well as all material icons. The final design system file is meant for JDRF's vendors to grab and use in their projects so it needs to have all the custom/Bootstrap components listed on the demo (gh-pages).
