### ISSUE TITLE
Broken layout when flex is enabled

### ISSUE THREAD

**Issue by briansaycocie** [JDRF/design-system#76]
Bootstrap supports [flexbox](https://v4-alpha.getbootstrap.com/getting-started/flexbox/) usage by adding `$enable-flex: true;` to _variables.scss. When I add this to `./design-system/src/scss/_variables.scss`, the layout of the documentation site breaks causing the main content area to overlap the sidebar navigation.

![ifsbbhsbic](https://cloud.githubusercontent.com/assets/1328262/15937326/06b6c90c-2e34-11e6-8a60-3ddc2489c937.gif)

**Comment by fuhton** [comment]
While this is awesome, this should be marked as a future enhancement. Browser support is not enabled for IE9 and there are some major issues in IE10 - these bugs are most definitely going to affect the grid. We could use a 3rd party plugin like [Flexibility](https://github.com/10up/flexibility), but I'm not comfortable requiring use of our JS file at this time.

Most of these known issues are based on facts from [Bootstrap](https://v4-alpha.getbootstrap.com/getting-started/flexbox/#browser-support)

**Comment by fuhton** [comment]
@RachelRVasquez This is #2 .

**Comment by RachelRVasquez** [comment]
@fuhton For this ticket, are we looking to fix IE10 bugs related to enabling flexbox along with finding some way to support or fallback in IE9? Due to JDRF's project history so far, from my experience, they've required IE9 so intentionally allowing crucial structures in the DS to break for a preference to flexbox doesn't seem like the best route to take with this. However, I'm open to thoughts and opinions?

I can also put some time into researching this further so we can get a better sense of the LOE?

**Comment by RachelRVasquez** [comment]
@fuhton Spent a little more time looking into this. The problems we're encountering w/ flexbox seems to be an issue w/ how we've set up Fabricator vs Bootstrap itself. If we set `.ds-row` to `flex-wrap: nowrap;`, that seems to solve the problem except there's something else in our component's markup still breaking it. Currently investigating.

**Comment by fuhton** [comment]
Sounds good. Let me know what you find.

**Comment by RachelRVasquez** [comment]
@fuhton Resolved and tested across all major browsers and IE9-11. Looks like we were able to resolve it with some CSS troubleshooting.

https://github.com/JDRF/design-system/pull/377

**Comment by fuhton** [comment]
@RachelRVasquez Merged and tested locally.
